Validator organic job fixes
backend-developers-ltd/ComputeHorde pull request #121
Opened 2024-06-04 06:31 UTC by andreea-popescu-reef

2024-06-04 14:50 UTC, mpnowacki-reef requested changes

2024-06-04 14:50 UTC, mpnowacki-reef commented on validator/app/src/compute_horde_validator/validator/management/commands/debug_run_organic_job.py
> +            print(f"\nJob {job_request.uuid} not found in OrganicJob table")
what it mean actually when it happens? I'm afraid that a printed message that doesn't look that scary, no sentry notification and exit status 0 might give users the wrong impressions of no disaster happening. Anyway did that happen to you in testing? does this command wait until the job succeeds or fails? or should the user check the progress in the admin panel?

2024-06-04 14:50 UTC, mpnowacki-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        job_request.status_message = f"job failed to trigger due to: {e}"
doesn't this need a logger.exception so sentry hears about it? This is not a failure that's part of the process, right?

2024-06-04 14:50 UTC, mpnowacki-reef commented on validator/app/src/compute_horde_validator/validator/tests/test_commands.py
> +def test_command():
```suggestion
def test_debug_run_organic_job_command():
```

2024-06-04 14:50 UTC, mpnowacki-reef commented on validator/app/src/compute_horde_validator/validator/admin.py
> +        if organic_job:
what if it's not there? maybe the whole redirect is not a good idea, maybe there should be an FK between the two models and a link you can click? with a comment saying "click here to track progress"

2024-06-05 01:34 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/admin.py
> +        if organic_job:
my ideea was that if the job is successfully triggered to redirect to the organic job view so the users tracks that - if there's a job trigger error the user will see the job request page and see the error there
I'll look into adding comments

2024-06-05 01:36 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        job_request.status_message = f"job failed to trigger due to: {e}"
this will be hit only by manually creating a job (cli or admin) - the error will be propagated to the user
I guess the most common error would be not finding the miner hotkey in the subtensor / bittensor wallet related
I'll add a log anyway

2024-06-05 01:49 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/management/commands/debug_run_organic_job.py
> +            print(f"\nJob {job_request.uuid} not found in OrganicJob table")
yes, there will be prints from the `notify_job_status_update` callback about the job progressing - admin panel should not be necessary
this happens when the job was not triggered successfully - will change the log to reflect that

2024-06-05 07:18 UTC, mpnowacki-reef commented on validator/app/src/compute_horde_validator/validator/admin.py
> +    miner = forms.CharField(
I think this should be a related field with autocomplete so it's impossible to select a non existent or blacklisted miner.

2024-06-05 07:19 UTC, mpnowacki-reef commented on validator/app/src/compute_horde_validator/validator/admin.py
> +    def clean(self):
if the miner field has autocomplete then this method is unnecessary

2024-06-05 08:23 UTC, mzukowski-reef requested changes

2024-06-05 08:23 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tests/test_commands.py
> +    sys.stdout = buf
overriding sys.stdout feels really wrong... if *really* needed then https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout but still it is global side-effect - really don't like it

I don't think we need to test if debug info is printed on stdout - if really needed, maybe we should make it logging and then capture logs in tests

2024-06-05 08:23 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tests/test_commands.py
> +        assert True
https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.raises

2024-06-05 08:23 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tests/test_commands.py
> +    sys.stdout = buf
same as above

2024-06-05 08:23 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tests/test_commands.py
> +    sys.stdout = buf
again stdout :)

2024-06-05 08:23 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tests/test_commands.py
> +    sys.stdout = buf
once again stdout

2024-06-05 08:48 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/tests/test_commands.py
> +    sys.stdout = buf
but that's not debug info for the cli user

2024-06-05 08:55 UTC, andreea-popescu-reef commented
so it looks like:
```
(nenv) ~/ComputeHorde/validator/app/src [validatorfixes] > python3 manage.py debug_run_organic_job --miner_hotkey 5CPhGRp4cdEG4KSui7VQixHhvN5eBUSnMYeUF5thdxm4sKtz --timeout 0 --docker_image python:3.11-slim  --raw_scrip "print(\"HELLOWORLD\")"
DEBUG 2024-06-05 07:38:45,570 asyncio Using selector: EpollSelector
DEBUG 2024-06-05 07:38:45,573 substrateinterface.base Connecting to ws://3.91.62.249:9946 ...
DEBUG 2024-06-05 07:38:46,035 substrateinterface.base RPC request #1: "system_chain"
INFO 2024-06-05 07:38:46,484 bittensor  - Connected to unknown network and ws://3.91.62.249:9946. - 
DEBUG 2024-06-05 07:38:46,486 substrateinterface.base RPC request #2: "chain_getHeader"
2024-06-05 07:38:46.484 |       INFO       |  - Connected to unknown network and ws://3.91.62.249:9946. - 
DEBUG 2024-06-05 07:38:46,714 substrateinterface.base RPC request #3: "rpc_methods"
DEBUG 2024-06-05 07:38:46,943 substrateinterface.base RPC request #4: "chain_getHead"
DEBUG 2024-06-05 07:38:47,171 substrateinterface.base RPC request #5: "chain_getHeader"
DEBUG 2024-06-05 07:38:47,399 substrateinterface.base RPC request #6: "state_getRuntimeVersion"
DEBUG 2024-06-05 07:38:47,628 substrateinterface.base RPC request #7: "state_getMetadata"
DEBUG 2024-06-05 07:38:49,022 substrateinterface.base Retrieved metadata for 185 from Substrate node
DEBUG 2024-06-05 07:38:49,028 substrateinterface.base Add PortableRegistry from metadata to type registry
DEBUG 2024-06-05 07:38:49,032 substrateinterface.base RPC request #8: "state_call"
DEBUG 2024-06-05 07:38:49,283 substrateinterface.base RPC request #9: "chain_getHeader"
Job successfully triggered

Processing job request: uuid: 33749a16-ebde-4456-97e4-802e2ab2e0c2 - miner hotkey: 5CPhGRp4cdEG4KSui7VQixHhvN5eBUSnMYeUF5thdxm4sKtz
ERROR 2024-06-05 07:38:49,994 compute_horde_validator.validator.miner_driver Miner 5CPhGRp4cdEG4KSui7VQixHhvN5eBUSnMYeUF5thdxm4sKtz(34.202.231.252:8000) timed out out while preparing executor for job 33749a16-ebde-4456-97e4-802e2ab2e0c2 after 300 seconds

job status: failed Miner timed out while preparing executor after 300 seconds

Job 33749a16-ebde-4456-97e4-802e2ab2e0c2 done processing
```


```
(nenv) ~/ComputeHorde/validator/app/src [validatorfixes] > python3 manage.py debug_run_organic_job --miner_hotkey 5CPhGRp4cdEG4KSui7VQixHhvN5eBUSnMYeUF5thdxm4sKtz --timeout 99 --docker_image python:3.11-slim  --raw_scrip "print(\"HELLOWORLD\")"   
DEBUG 2024-06-05 07:37:42,880 asyncio Using selector: EpollSelector
DEBUG 2024-06-05 07:37:42,884 substrateinterface.base Connecting to ws://3.91.62.249:9946 ...
DEBUG 2024-06-05 07:37:43,335 substrateinterface.base RPC request #1: "system_chain"
INFO 2024-06-05 07:37:43,772 bittensor  - Connected to unknown network and ws://3.91.62.249:9946. - 
DEBUG 2024-06-05 07:37:43,774 substrateinterface.base RPC request #2: "chain_getHeader"
2024-06-05 07:37:43.772 |       INFO       |  - Connected to unknown network and ws://3.91.62.249:9946. - 
DEBUG 2024-06-05 07:37:43,997 substrateinterface.base RPC request #3: "rpc_methods"
DEBUG 2024-06-05 07:37:44,221 substrateinterface.base RPC request #4: "chain_getHead"
DEBUG 2024-06-05 07:37:44,444 substrateinterface.base RPC request #5: "chain_getHeader"
DEBUG 2024-06-05 07:37:44,666 substrateinterface.base RPC request #6: "state_getRuntimeVersion"
DEBUG 2024-06-05 07:37:44,889 substrateinterface.base RPC request #7: "state_getMetadata"
DEBUG 2024-06-05 07:37:46,481 substrateinterface.base Retrieved metadata for 185 from Substrate node
DEBUG 2024-06-05 07:37:46,491 substrateinterface.base Add PortableRegistry from metadata to type registry
DEBUG 2024-06-05 07:37:46,497 substrateinterface.base RPC request #8: "state_call"
DEBUG 2024-06-05 07:37:47,156 substrateinterface.base RPC request #9: "chain_getHeader"
Job successfully triggered

Processing job request: uuid: 33e8643f-234b-4bbd-a451-399de486f441 - miner hotkey: 5CPhGRp4cdEG4KSui7VQixHhvN5eBUSnMYeUF5thdxm4sKtz
INFO 2024-06-05 07:37:48,071 compute_horde_validator.validator.synthetic_jobs.utils Received info about another job: job_uuid='3410e097-3890-4960-9eda-6dce9a8f0710' message_type=<RequestType.V0JobFailedRequest: 'V0JobFailedRequest'> docker_process_exit_status=None docker_process_stdout='' docker_process_stderr=''
INFO 2024-06-05 07:37:48,706 compute_horde_validator.validator.synthetic_jobs.utils Miner 5CPhGRp4cdEG4KSui7VQixHhvN5eBUSnMYeUF5thdxm4sKtz(34.202.231.252:8000) accepted job
DEBUG 2024-06-05 07:37:53,983 compute_horde_validator.validator.miner_driver Miner 5CPhGRp4cdEG4KSui7VQixHhvN5eBUSnMYeUF5thdxm4sKtz(34.202.231.252:8000) ready for job: job_uuid='3
3e8643f-234b-4bbd-a451-399de486f441' message_type=<RequestType.V0ExecutorReadyRequest: 'V0ExecutorReadyRequest'>

job status: accepted Miner accepted job
INFO 2024-06-05 07:37:54,703 compute_horde_validator.validator.miner_driver Miner took 0.7188029289245605 seconds to finish 33e8643f-234b-4bbd-a451-399de486f441
INFO 2024-06-05 07:37:54,703 compute_horde_validator.validator.miner_driver Miner 5CPhGRp4cdEG4KSui7VQixHhvN5eBUSnMYeUF5thdxm4sKtz(34.202.231.252:8000) finished: job_uuid='33e8643f-234b-4bbd-a451-399de486f441' message_type=<RequestType.V0JobFinishedRequest: 'V0JobFinishedRequest'> docker_process_stdout='HELLOWORLD\n' docker_process_stderr=''

job status: completed Miner finished
stderr: 
stdout: HELLOWORLD

Job 33e8643f-234b-4bbd-a451-399de486f441 done processing
```


```
(nenv) ~/ComputeHorde/validator/app/src [validatorfixes] > python3 manage.py debug_run_organic_job --miner_hotkey 5E5GRiFLWP7a5xdZVENFRHfRDYCktmBXE8hPY8AmnAa65itH --timeout 3 --docker_image python:3.11-slim  --raw_scrip "print("HELLOWORLD")"
DEBUG 2024-06-05 08:54:12,968 asyncio Using selector: EpollSelector
DEBUG 2024-06-05 08:54:12,971 substrateinterface.base Connecting to ws://3.91.62.249:9946 ...
DEBUG 2024-06-05 08:54:13,439 substrateinterface.base RPC request #1: "system_chain"
INFO 2024-06-05 08:54:13,894 bittensor  - Connected to unknown network and ws://3.91.62.249:9946. - 
2024-06-05 08:54:13.894 |       INFO       |  - Connected to unknown network and ws://3.91.62.249:9946. - 
DEBUG 2024-06-05 08:54:13,897 substrateinterface.base RPC request #2: "chain_getHeader"
DEBUG 2024-06-05 08:54:14,128 substrateinterface.base RPC request #3: "rpc_methods"
DEBUG 2024-06-05 08:54:14,361 substrateinterface.base RPC request #4: "chain_getHead"
DEBUG 2024-06-05 08:54:14,592 substrateinterface.base RPC request #5: "chain_getHeader"
DEBUG 2024-06-05 08:54:14,823 substrateinterface.base RPC request #6: "state_getRuntimeVersion"
DEBUG 2024-06-05 08:54:15,055 substrateinterface.base RPC request #7: "state_getMetadata"
DEBUG 2024-06-05 08:54:16,468 substrateinterface.base Retrieved metadata for 185 from Substrate node
DEBUG 2024-06-05 08:54:16,473 substrateinterface.base Add PortableRegistry from metadata to type registry
DEBUG 2024-06-05 08:54:16,477 substrateinterface.base RPC request #8: "state_call"
DEBUG 2024-06-05 08:54:16,731 substrateinterface.base RPC request #9: "chain_getHeader"
Job failed to trigger due to: Miner with hotkey='5E5GRiFLWP7a5xdZVENFRHfRDYCktmBXE8hPY8AmnAa65itH' not present in this subnetwork

Job ccca466f-17c0-496c-ad5f-852d06ec17be not found
```

2024-06-06 07:32 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tests/test_commands.py
> +    sys.stdout = buf
you actually missed here :)

2024-06-06 08:35 UTC, merged