COM-120 commit reveal weights
backend-developers-ltd/ComputeHorde pull request #185
Opened 2024-07-30 22:57 UTC by agoncharov-reef

This PR adds functionality to commit & (later) reveal weights instead of simple setting weights.
Here's a description from BT team: https://docs.bittensor.com/subnets/commit-reveal

New workflow:
0. `do_set_weights` celery task reads `commit_reveal_weights_enabled` hyperparameter
1. if `commit_reveal_weights_enabled` is `True`:
  - the task commits the hashed weights to the network and stores payload in `Weights` model instance
  - the task `reveal_scores` is run each minute and searched for not-yet-revealed `Weights` which are older than `commit_reveal_weights_interval - reveal_in_advance_num_blocks`, and reveals them
2. if  `commit_reveal_weights_enabled` is `False`, ol' good `set_weights` is called which sets weights immediately and they become available to everyone
3. if metagraph sucks and it's impossible to get value of `commit_reveal_weights_enabled`, noth `commit_weights` and `set_weights` are called to see which one will work

# Commit reveal interval
I tried to experiment with `commit_reveal_weights_interval`. Docs say:
> Specify the desired number of blocks of delay before revealing the weights, by using the new subnet hyperparameter commit_reveal_weights_interval (integer).

It is expected that weights should be revealed any time _after_ this interval, however during local testing I was able to reveal weights before that period (which is surprising to me) and some time after that period has passed. If revealing too late, the network will throw an error. I haven't figured out what are the exact rules, so we start trying to reveal weights a bit in advance (`reveal_in_advance_num_blocks: int = 10`).

# Weights are ints!
Also I noticed that in order to hash weights before committing them, the weight values must be `int`s. It was a surprise to me cause I thought they could be float, so if they can indeed then let's discuss wtf is going on.

# How to activate (or deactivate)
To enable the feature, one should modify subnet hyperparams:
```
btcli sudo set hyperparameters --netuid=xx --param commit_reveal_weights_enabled --value True --wallet.name local-owner
btcli sudo set hyperparameters --netuid=12 --param commit_reveal_weights_interval --value 20 --wallet.name local-owner
```

2024-07-31 09:14 UTC, mzukowski-reef requested changes

2024-07-31 09:14 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        hyperparams = subtensor.get_subnet_hyperparameters(netuid=settings.BITTENSOR_NETUID)
don't relay on hyperparam here - if there is unrevealed weights object we should try to reveal it - if commit_reveal_weights_enabled is not enabled then when creating weights in db we should mark them as revealed

2024-07-31 09:14 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        commit_reveal_weights_interval = 0
we should have better default

2024-07-31 09:14 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +    for weights in unrevealed_weights:
I think that @ppolewicz said that you can reveal only the last commited weights - if I heard correctly then we should prevent commiting weights if previous one are no expired and still unrevealed - and then in this place we would reveal only latest weights

2024-07-31 16:09 UTC, agoncharov-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        hyperparams = subtensor.get_subnet_hyperparameters(netuid=settings.BITTENSOR_NETUID)
Yes, makes sense, thank you!
Although the second part is not true - we cannot create `Weights` when `commit_reveal_weights_enabled` is not enabled .

2024-07-31 16:17 UTC, agoncharov-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        commit_reveal_weights_interval = 0
The idea was: if we have no fucking clue what's the interval because of stupid broken metagraph or so, then fallback to "almost regular set-weight" == "commit weights and reveal as soon as possible". When metagraph is finally fixed, return back to regular interval. As far as I understand, when we introduce commit-reveal, cheaters won't try to eliminate it, and even if we fallback to zero interval for some moment, nobody will use it.

2024-07-31 16:36 UTC, agoncharov-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +    for weights in unrevealed_weights:
Thank you, good point!

2024-08-01 06:59 UTC, mzukowski-reef requested changes
we cant merge with failing tests

2024-08-01 06:59 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        if not is_success:
we should have some weight reveal system events - also we might think to send different event metadata for weight commit than weight setting

2024-08-02 10:26 UTC, merged