Remove old synthetic jobs flow
backend-developers-ltd/ComputeHorde pull request #206
Opened 2024-08-20 12:33 UTC by emnoor-reef

2024-08-21 07:57 UTC, mzukowski-reef requested changes

2024-08-21 07:57 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tests/test_utils.py
noooooooooo....... :D

without it we don't have any unit tests - I think I've made them kind of generic so it should not be that hard to adjust to new flow - it is kind of disturbing that new flow don't have unit tests

2024-08-21 22:11 UTC, emnoor-reef commented on validator/app/src/compute_horde_validator/validator/tests/test_utils.py
As I initially suspected, the tests took waaaaaay long to adjust to the new flow. :'(

There are some minor TODOs left in there. I'll look at them later (too exhausted now) :D

2024-08-22 10:26 UTC, mzukowski-reef approved these changes

2024-08-22 13:54 UTC, merged