feat: add automated version tagging for CI/CD pipeline
backend-developers-ltd/ComputeHorde pull request #229
Opened 2024-09-04 12:59 UTC by hiroyukikumazawa

#### Overview

This PR introduces a new GitHub Actions workflow, `common_tagging.yml`, that automates the tagging process for our CI/CD pipeline. The automated version tagging ensures consistent version management and supports changelog integration across different components of the Compute Horde monorepo. The tagging format follows `<year>.<month>.<day>-<index>`, incrementing if multiple releases occur on the same day.

#### Key Changes

- **New Workflow**: `common_tagging.yml` added to handle common tagging tasks.
  - **Inputs**:
    - `DIST_VERSION_PREFIX`: Prefix for the distribution (e.g., `executor-preprod`).
  - **Jobs**:
    - Determines the next tag based on the current date and existing tags.
    - Creates and pushes the next tag to the repository.

- **Updates to Existing Workflows**:
  - Workflows such as `executor_cd_preprod.yml` have been updated to utilize the new tagging workflow by calling `common_tagging.yml`.

#### Important Note: `ACTIONS_PAT` Secret

The `ACTIONS_PAT` secret is **critical** for the new tagging workflow to function correctly. It is a Personal Access Token (PAT) that allows the GitHub Actions runner to:
- Fetch all tags from the repository.
- Create and push new tags back to the repository.

##### Setting Up `ACTIONS_PAT`

1. **Generate a Personal Access Token (PAT):**
   - Go to your GitHub account's [Developer settings/Tokens (classic)](https://github.com/settings/tokens).
   - Click **"Generate new token (classic)"** and select the necessary permissions:
     - `repo` (Full control of private repositories).
     - `workflow` (Update GitHub Actions workflows).
   - Copy the generated token; **it will not be shown again.**

2. **Add the `ACTIONS_PAT` Secret to the Repository:**
   - Navigate to the repository's **Settings** > **Secrets and variables** > **Actions**.
   - Click **"New repository secret"**.
   - Name the secret `ACTIONS_PAT` and paste the copied token.

2024-09-12 11:02 UTC, hiroyukikumazawa commented
@ppolewicz 

In the tagging workflow, I have replaced the use of the personal access token (`ACTIONS_PAT`) with the GitHub-provided `GITHUB_TOKEN`.

**Important Note:**
To ensure the updated workflow functions correctly, we need to adjust the **Workflow permissions** settings in the repository's Actions settings. Please follow these steps:

1. Go to **Settings** > **Actions** > **General**.
2. Under **Workflow permissions**, ensure that "Read and write permissions" is selected.

2024-09-13 07:12 UTC, mzukowski-reef requested changes

2024-09-13 07:12 UTC, mzukowski-reef commented on .github/workflows/common_tagging.yml
> +  CHANGE_LOG_BRANCH: "staging"
unused? remove?

2024-09-13 09:59 UTC, hiroyukikumazawa commented on .github/workflows/common_tagging.yml
> +          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV
good point!

2024-09-13 10:02 UTC, hiroyukikumazawa commented on pyproject.toml
> +[tool.towncrier]
atm, the towncrier part is not used due to the conflict
but it's useful in the future

2024-09-13 13:37 UTC, hiroyukikumazawa commented on pyproject.toml
> +[tool.towncrier]
@mzukowski-reef what do you think?

2024-09-17 20:57 UTC, mzukowski-reef approved these changes

2024-12-03 11:59 UTC, closed without merging