answering prompts job
backend-developers-ltd/ComputeHorde pull request #240
Opened 2024-09-12 10:28 UTC by andreea-popescu-reef

2024-09-13 20:17 UTC, olzhasar-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +    return prompts
Why not:
```
return Prompt.objects.select_related('sample').filter(sample__workload_id=workload.id, answer__isnull=True)
```
? 😁

2024-09-13 20:17 UTC, olzhasar-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        for prompt in prompts:
If the server shuts down and the execution stops somewhere here, we will end up having inconsistent data.
We should consider having a separate sync function wrapped in an atomic block and call it with sync_to_async or smth

2024-09-13 20:17 UTC, olzhasar-reef commented on validator/app/src/compute_horde_validator/validator/tests/settings.py
> +TRUSTED_MINER_KEY = "fake_generation_miner_key"
Will we have just a single trusted miner for now?

2024-09-13 20:17 UTC, olzhasar-reef commented on validator/app/src/compute_horde_validator/validator/s3.py
> +async def download_json(s3_url: str):
I would call it just `download_file_content` or smth, cause the function doesn't necessarily assume json inside

2024-09-14 08:30 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/tests/settings.py
> +TRUSTED_MINER_KEY = "fake_generation_miner_key"
I thought that was the initial assumption - but can separate the vars anyway

2024-09-16 11:48 UTC, emnoor-reef commented on validator/app/src/compute_horde_validator/validator/synthetic_jobs/batch_run.py
> +async def get_llama_prompt_samples(ctx: BatchContext) -> PromptSample | None:
```suggestion
async def get_llama_prompt_samples(ctx: BatchContext) -> list[PromptSample] | None:
```

2024-09-16 11:53 UTC, emnoor-reef commented on validator/app/src/compute_horde_validator/validator/synthetic_jobs/generator/llama_prompts.py
> +        self.prompt_sample: PromptSample | None = prompt_sample
`self.prompt_sample` cannot be `None`. If there's no PromptSample, this generator should never be called in the first place. If it is None, this will fail in the synthetic jobs flow: https://github.com/backend-developers-ltd/ComputeHorde/blob/7c20ce09534112016ada8a0d3a4221568c818e28/validator/app/src/compute_horde_validator/validator/synthetic_jobs/batch_run.py#L1419-L1426

2024-09-16 12:21 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/synthetic_jobs/batch_run.py
> +    llama_prompt_samples = await get_llama_prompt_samples(ctx)
no - we only send llama to llama tasks executors https://github.com/backend-developers-ltd/ComputeHorde/pull/240/files/0b24ef06466029ae6530b3a379b3dcb086b56806#diff-399b6cde1b3f4939e5344ce72773b39b38e23cad3c26010f1b75736c6ff3ca31R807

2024-09-16 12:25 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/synthetic_jobs/generator/llama_prompts.py
> +        self.prompt_sample: PromptSample | None = prompt_sample
so there are 2 flows - one for the synthetic jobs where indeed it can't be None - and one for generating the answers for the workload (the workload contains multiple prompts associated with different prompt samples) where the prompt sample is not needed

2024-09-16 12:25 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/synthetic_jobs/generator/llama_prompts.py
> +        self.prompt_sample: PromptSample | None = prompt_sample
I'll try to add clearer check for it

2024-09-16 12:28 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        async_to_sync(answer_prompts)(workload)
good point - I'll handle it

2024-09-16 12:30 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/settings.py
> +        "schedule": timedelta(minutes=10),
yeah - I'm trying to run tests with smaller values to check for errors - the actual env vars values (not just the scheduling, but the timeouts for jobs too) will need to be figured out when we deploy

2024-09-16 12:32 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/cross_validation/prompt_answering.py
> +        logger.warning("Prompt generation miner not configured, skipping prompt generation")
it should be trusted miner - wouldn't we just add executors instead of additional miners if needed though?

2024-09-16 15:55 UTC, olzhasar-reef commented on validator/app/src/compute_horde_validator/validator/cross_validation/prompt_answering.py
> +        logger.warning("Prompt generation miner not configured, skipping prompt generation")
The thing is, I don't think we are currently able to properly route jobs for multiple executor classes out of the box. We added a general ability for that, but there needs to be a subclassed `DockerExecutorManager` with overwritten `get_manifest` method for this to work.
So I assume the idea for the upcoming release was to have different miners for now. but I am not sure if a single one is okay though, maybe it is. Let's discuss this tomorrow

2024-09-16 16:03 UTC, olzhasar-reef commented on validator/app/src/compute_horde_validator/validator/synthetic_jobs/batch_run.py
> +    llama_prompt_samples = await get_llama_prompt_samples(ctx)
Oh, I see. Maybe we can skip the query altogether then if we don't have such executors? Either here or inside the get_llama_prompt_sample func.
But that's a minor thing though, can be ignored for now

2024-09-17 22:04 UTC, mzukowski-reef requested changes

2024-09-17 22:04 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        async_to_sync(generate_prompts)()
we need to lock local miner here - only one task can use local miner at the same time

2024-09-17 22:04 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +            get_advisory_lock(LockType.ANSWERING_PROMPTS)
don't know if we want to lock for all workloads - maybe we need to lock per workload allowing switching between prompt answering and generating

2024-09-18 06:33 UTC, andreea-popescu-reef commented on miner/app/src/compute_horde_miner/miner/miner_consumer/validator_interface.py
> +            await prepare_receipts()
ah I see - was triggering this from a local command without celery and was breaking  - will revert

2024-09-18 07:25 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
>      seed = random.randint(0, 1000000)
wait - that would not fit into the BigIntegerField
I guess we would be fine with 64bit?

2024-09-18 11:11 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +            get_advisory_lock(LockType.ANSWERING_PROMPTS)
we should always prioritize answering so it should be fine to no switch from this task unless it's finished - if there are unanswered workloads we don't gain anything by generating or sampling more

answering will run when there are workloads available - will not run otherwise
sampling will run when there are not enough workloads prepped
^ these can be triggered frequently as they will stop when there's nothing left to do
generation can run inbetween to refresh the db prompt series - I assume we'll be running only generation when deploying to fill the db and then switch on the other tasks

2024-09-18 12:09 UTC, mzukowski-reef requested changes

2024-09-18 12:09 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/settings.py
> +    # "llm_prompt_generation": {
I kind don't get it how we plan it to interact - running them every 10min with 10min timeout seems kind of wrong - the idea was I think to have like a "router" task that would see what should be done and schedule a small batch of work - if this "router" would see that some work is being done it should finish task and let it check again in next run

current timeouts for tasks are I think wrong - we select everything in database (workload, series) and just run the flow for every object - this might not be aligned with timeout - we should take as much work as timeout allows (with some buffer) and run it

I think this is like design discussion - current implementation is ok for testing, but we need to decide for target solution

2024-09-18 12:48 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/settings.py
> +    # "llm_prompt_generation": {
the timeouts (and most of the new vars values) are not decided yet - we should at least have an idea of how long a generation/answering task takes before setting them. ~ 10m were testing placeholder.

yeah, I stuck with the idea of having separate tasks

to maximize the amount of work between synthetic jobs: we can just trigger generation -> sampling -> answering.  We can generate and sample exactly enough prompts/workloads for an answering run.

though I'm still confused with the generation tasks - I though we wanted to run it a lot in the beginning until we have enough prompt series and then use those / not continue generating than much

2024-09-25 07:41 UTC, merged