Fix commit reveal
backend-developers-ltd/ComputeHorde pull request #247
Opened 2024-09-19 20:30 UTC by olzhasar-reef

2024-09-20 08:58 UTC, mzukowski-reef requested changes

2024-09-20 08:58 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +        if (
```
commit_window_start = current_interval.start + commit_start_offset
commit_window_end = current_interval.stop - commit_end_buffer

if not (commit_window_start <= current_block < commit_window_end):

```
or maybe just put `not` outside bool expression - but my version seems more readable :)

2024-09-20 08:58 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +                "Outside of commit window, skipping, current block: %s, interval: %s, offset: %s, buffer: %s",
Can we have "somewhere" a nice summary what is happenning here...?

I mean - how cycle start/end interacts with weights commiting and weights revealing, why we have start-offset... 

why we wait with commit till end of a cycle - do we have to?

what is the logic of computing emissions for given cycle - possible cases analyzed... 

it is really hard to review this in terms of logic if nothing is documented

2024-09-24 11:34 UTC, olzhasar-reef commented on validator/app/src/compute_horde_validator/validator/tasks.py
> +class CommitRevealInterval:
Reusing the logic for calculating cycles was the first thing I had in mind.
But the issue is that the commit reveal intervals calculation is not tied to subnets in the actual subtensor code.
And we could use a netuid of 0, but this would arguably make things more confusing.
Speaking of dynamic params, for now it's easier to share the common logic like that (cause we still use dynamic params everywhere), but I made everything overridable in the __init__ to have a bit of a room there.

2024-09-24 13:20 UTC, mzukowski-reef approved these changes

2024-09-24 13:21 UTC, merged