Split celery tasks
backend-developers-ltd/ComputeHorde pull request #292
Opened 2024-10-29 13:15 UTC by kkowalski-reef

- Replaced single-container celery setup with one container per queue, one master celery process per container and multiple worker processes per master process. This makes it so that there's one top-level process in the container, and we avoid `celery multi` which, by spawning celery with `--detach`, makes it sometimes hang on startup: https://github.com/celery/celery/discussions/8141
- Added new env var: `CELERY_CONCURRENCY`, replacing `CELERY_MASTER_CONCURRENCY` and `CELERY_WORKER_CONCURRENCY`
- Moved `manage.py migrate` from celery's entrypoint script to the main django app`s entrypoint so that multiple celery processes don't try to migrate the DB at the same time.

2024-10-30 07:54 UTC, emnoor-reef requested changes

2024-10-31 12:07 UTC, emnoor-reef commented on validator/envs/prod/docker-compose.yml
> +    command: ./celery-entrypoint.sh -Q weights -E -l INFO -c ${CELERY_CONCURRENCY}
You also need to provide `-n` flag with unique names (may be same as queue names?) for them to properly "mingle".

2024-10-31 20:04 UTC, emnoor-reef commented on validator/envs/prod/docker-compose.yml
> +    command: ./celery-entrypoint.sh -Q weights -E -l INFO -c ${CELERY_CONCURRENCY}
Though I am not sure. Our current celery config does not set names and the workers do not mingle. I don't know what it means though. 🤷‍♂️

2024-11-06 14:25 UTC, olzhasar-reef commented on validator/app/envs/prod/celery-entrypoint.sh
> +CELERY_MAX_TASKS_PER_CHILD=${CELERY_MAX_TASKS_PER_CHILD:-10}
Is that an informed decision?
The default value of 10 feels quite small, restarting the worker after every 10 tasks might be an unnecessary overhead.
Do we even have memory problems somewhere?

2024-11-06 14:25 UTC, olzhasar-reef commented on validator/envs/runner/data/docker-compose.yml
> +  celery-worker-weights:
Are we really sure we want that many dedicated workers?
Commit and reveal operations happen just once per tempo, the worker will just sit silently the rest of the time occupying a good memory portion.
And there is no downscaling either
It's probably reasonable to have separate workers for synthetic jobs and llm generation, but I'm not so sure about everything else. Going from 2 workers to 5 all of a sudden is quite a big jump

2024-11-07 12:23 UTC, olzhasar-reef approved these changes

2024-11-07 12:27 UTC, olzhasar-reef commented on validator/app/envs/prod/celery-entrypoint.sh
> +CELERY_MAX_TASKS_PER_CHILD=${CELERY_MAX_TASKS_PER_CHILD:-10}
Leaving this for you to decide, I feel like something around 30 would more reasonable

2024-11-07 14:17 UTC, emnoor-reef approved these changes

2024-11-07 14:30 UTC, merged