Add block number cache
backend-developers-ltd/ComputeHorde pull request #353
Opened 2024-12-20 11:35 UTC by slawomir-gorawski-reef

2024-12-28 15:50 UTC, mpnowacki-reef requested changes
I really like your code, it's nice and concise. One thing lacking here is: a description on how this app is supposed to be used (and it's use in current projects: miner and vali). should projects call `get_current_block()`? is this the one and only public interface method? What about the task? should it be added to  beat config?

One design decicion i don't agree with is `return cache_current_block()` in `get_current_block()` (provided this is the public method that should be used by projects. This is IO that can be idefinitely blocking. Also it's not suitable to be used in async contexts. BTW is there a nice way to read the cached key (which i guess is in redis) in async functions? If the cache is empty then this function should wait fo a set period of time for it to be populated, maybe schedule a task for ti to happen (but do the subtensor IO blockingly) and raise an exception if it doesn't get populated. Don't block the whole app.

2024-12-28 15:50 UTC, mpnowacki-reef commented on compute_horde/compute_horde/blockchain/block_cache.py
> +    subtensor = get_subtensor(network=settings.BITTENSOR_NETWORK)
this takes ~ 0.5s, is there any reason to get a new instance of the subtensor everytime?

2024-12-28 15:50 UTC, mpnowacki-reef commented on compute_horde/pyproject.toml
> +    "celery>=5.3.0",
there should be a limit, sth like `<6` cause even `from celery import shared_task` might break with a major release, right?

2024-12-28 15:50 UTC, mpnowacki-reef commented on compute_horde/compute_horde/settings.py
> +INSTALLED_APPS = [
what is this file for anyway?

2024-12-28 15:50 UTC, mpnowacki-reef commented on compute_horde/uv.lock
> +version = "5.5.0rc3"
is this correct? we want a release candidate to be used in production?

2024-12-30 11:38 UTC, slawomir-gorawski-reef commented on compute_horde/uv.lock
> +version = "5.5.0rc3"
Good catch, no. We have `prerelease = "allow"` in this project's uv settings, I think for bt-decode, but it causes uv to resolve dependencies to unstable releases. I managed to fix it manually but it can happen again if we keep it as is.

2024-12-30 11:38 UTC, slawomir-gorawski-reef commented on compute_horde/compute_horde/settings.py
> +INSTALLED_APPS = [
Tooling – at least django-stubs needs it, it seems.

2024-12-30 11:43 UTC, slawomir-gorawski-reef commented on compute_horde/compute_horde/blockchain/block_cache.py
> +    subtensor = get_subtensor(network=settings.BITTENSOR_NETWORK)
No reason, fixed.

2024-12-30 11:49 UTC, slawomir-gorawski-reef commented
Yeah, good point about async, I didn't think of that. I changed the main function to be async with a configurable timeout that raises an exception if the timeout is exceeded.

Reading from the cache itself is not async and Django doesn't support that yet.

It's Redis and it seems fast, so maybe it's fine to leave it as is?
Otherwise, I think the best solution would be to ditch `django.core.cache` and use an async Redis client from redis-py directly.

2024-12-30 15:00 UTC, mpnowacki-reef commented on compute_horde/uv.lock
> +version = "5.5.0rc3"
Please create a ticket in jira

2024-12-30 15:05 UTC, mpnowacki-reef commented
yeah i guess sync redis access is fine

2024-12-30 15:07 UTC, mpnowacki-reef commented
These points

>Usage:
>
>    Add compute_horde.blockchain to INSTALLED_APPS in the settings module.
>    Add compute_horde.blockchain.tasks.update_block_cache as a celery beat task with some reasonable frequency (like 1 or 2 s)
>    To get the current block number from cache, use aget_current_block (or get_current_block).

should be somewhere in the readme of this module or some docstring or some place in the repo.

2024-12-30 15:08 UTC, mpnowacki-reef commented on compute_horde/compute_horde/blockchain/block_cache.py
> +@functools.cache
this is gonna be primarily used by a celery task. Does `functools.cache` work nicely with celery tasks?

2025-01-02 10:07 UTC, slawomir-gorawski-reef commented on compute_horde/compute_horde/blockchain/block_cache.py
> +@functools.cache
Yup, I checked it, works as expected

2025-01-02 10:21 UTC, slawomir-gorawski-reef commented
Added to README.

> BTW can beat schedule tasks every second?

It's supported. As for performance, on my (weak) VM the tasks are completed within ~0.1s and the Redis queue seems very fast.
It doesn't have actual load from other tasks, but most of these are routed to separate queues and workers, so I'd say it should probably be still ok.

<img width="1975" alt="Screenshot 2025-01-02 at 11 19 52" src="https://github.com/user-attachments/assets/3ee1b4c7-fa4f-4932-973f-e1476e4307e2" />

2025-01-03 15:45 UTC, mpnowacki-reef approved these changes

2025-01-03 15:45 UTC, merged