Admin panel
backend-developers-ltd/ComputeHorde pull request #68
Opened 2024-04-12 15:08 UTC by andreea-popescu-reef

https://reeftechnologies.atlassian.net/browse/COM-67
https://reeftechnologies.atlassian.net/browse/COM-51

2024-04-15 11:49 UTC, agoncharov-reef reviewed
Nice! :+1:

2024-04-15 11:49 UTC, agoncharov-reef commented on miner/app/src/compute_horde_miner/miner/admin.py
> +        # If database not setup skip creating default admin
Is it possible that DB is not set up?
If yes then it's better to catch specific exception, not `Exception`.

2024-04-15 11:49 UTC, agoncharov-reef commented on miner/app/src/compute_horde_miner/miner/admin.py
> +        admin_password = os.getenv("DEFAULT_ADMIN_PASSWORD")
Nitpick: I'd define it in settings (`DEFAULT_ADMIN_PASSWORD = env("DEFAULT_ADMIN_PASSWORD", default=None)`), so that here we use `settings.DEFAULT_ADMIN_PASSWORD`. I think defining settings in `settings.py` is better than reading settings from env vars in random place of an application.

2024-04-15 11:49 UTC, agoncharov-reef commented on miner/app/src/compute_horde_miner/miner/admin.py
> +            admin_user.save()
It's redundant:
> create_superuser(username, email=None, password=None, **extra_fields)[¶](https://docs.djangoproject.com/en/5.0/ref/contrib/auth/#django.contrib.auth.models.UserManager.create_superuser)
> Creates, saves and returns a [User](https://docs.djangoproject.com/en/5.0/ref/contrib/auth/#django.contrib.auth.models.User).

2024-04-15 11:49 UTC, agoncharov-reef commented on miner/app/src/compute_horde_miner/miner/admin.py
> +maybe_create_default_admin()
I think all this should go to `app.ready()`, something like in this question description: https://stackoverflow.com/questions/60562025/automatically-create-django-model-instances-at-startup-with-empty-database

2024-04-15 11:49 UTC, agoncharov-reef commented on miner/app/src/compute_horde_miner/miner/miner_consumer/validator_interface.py
> +                logger.info(f"Declining job {msg.job_uuid} from blacklisted validator: self.validator_key")
f-string missing interpolation near `self.validator_key` :P

2024-04-15 11:49 UTC, agoncharov-reef commented on miner/app/src/compute_horde_miner/miner/models.py
> +        return self.validator.public_key
Nitpick: Since the model has only one field, it could be just model field (`is_blacklisted`)

2024-04-15 11:49 UTC, agoncharov-reef commented on validator/app/src/compute_horde_validator/validator/admin.py
> +            admin_user = User.objects.create_superuser(username='admin', email='admin@admin.com', password=admin_password)
Better put those values in `settings.py`, magic strings aren't good

2024-04-15 11:49 UTC, agoncharov-reef commented on validator/app/src/compute_horde_validator/validator/admin.py
> +maybe_create_default_admin()
+ same notes as in miner's admin, won't copy here

2024-04-15 11:49 UTC, agoncharov-reef commented on validator/nginx/templates/default.conf.template
> +    listen 127.0.0.1:80 default_server;
Maybe I misunderstand. So this gonna work only inside the container, right? How are users supposed to get there?

2024-04-15 11:50 UTC, agoncharov-reef commented on miner/app/src/compute_horde_miner/miner/models.py
> +        return self.validator.public_key
(no need for action here)

2024-04-15 12:21 UTC, andreea-popescu-reef commented on miner/app/src/compute_horde_miner/miner/admin.py
> +        # If database not setup skip creating default admin
it should no longer be possible after moving this to post migrate

2024-04-15 14:59 UTC, andreea-popescu-reef commented on validator/nginx/templates/default.conf.template
> +    listen 127.0.0.1:80 default_server;
ah no, that should have been on the docker-compose port - the admin panel should only be visible via ssh on the machine

2024-04-25 12:59 UTC, mzukowski-reef requested changes

2024-04-25 12:59 UTC, mzukowski-reef commented on validator/app/src/compute_horde_validator/validator/admin.py
> +class AddOnlyAdmin(admin.ModelAdmin):
I know that this was specified in a task, but allowing creating jobs is wrong right now - there is no logic that would make it usable - we should not have "fake" features

2024-04-25 13:05 UTC, andreea-popescu-reef commented on validator/app/src/compute_horde_validator/validator/admin.py
> +class AddOnlyAdmin(admin.ModelAdmin):
I'll comment out the Jobs  views for now

2024-04-25 14:13 UTC, mzukowski-reef approved these changes

2024-04-25 22:31 UTC, merged