Job receipts
backend-developers-ltd/ComputeHorde pull request #91
Opened 2024-05-09 06:21 UTC by emnoor-reef

2024-05-09 22:13 UTC, pawelpolewicz commented on miner/app/src/compute_horde_miner/miner/miner_consumer/validator_interface.py
> +            logger.debug(f'Received receipt for job_uuid: {msg.payload.job_uuid}')
should be INFO and should contain validator hotkey, time_took and score so that people can grep and parse it out from the logs easily

2024-05-14 12:40 UTC, mzukowski-reef requested changes

2024-05-14 12:40 UTC, mzukowski-reef commented on miner/app/src/compute_horde_miner/miner/utils.py
> +    # TODO: use a lock to prevent simultaneous write to zip file
this TODO is misleading - current implementation is asyncio blocking, so we actually have this lock :D but even then this code is wrong - you can run this after two new receipts and older query would race with newer query in that way that old receipts that don't have newst object would overwrite a newer snapshot (it would be fixed after next recepit, but still)

2024-05-14 12:40 UTC, mzukowski-reef commented on miner/app/src/compute_horde_miner/miner/receipt_store/local.py
> +        with zipfile.ZipFile(filepath, mode='w', compression=zipfile.ZIP_LZMA) as zf:
I know that the design was "make it zip" - but I still give myself right to complain :P

2024-05-14 12:40 UTC, mzukowski-reef commented on miner/app/src/compute_horde_miner/miner/models.py
> +    score = models.FloatField()
I am concerned about "float stability" - we generate signature of float dumped to string - and then we post this over network, json loads, then pydantic parse to float, then check signature - then store in database, then read from database and dumps to json...  same with DurationField - it is float in json - don't know what it is in database - DateTime? also not sure...

2024-05-14 12:40 UTC, mzukowski-reef commented on miner/app/src/compute_horde_miner/miner/receipt_store/base.py
> +                miner_hotkey=settings.BITTENSOR_WALLET().hotkey.ss58_address,
miner can change key without changing database (I think) - then we actually should be filtering out old receipts

2024-05-15 07:41 UTC, emnoor-reef commented on miner/app/src/compute_horde_miner/miner/utils.py
> +    await JobReceipt.objects.filter(time_started__lt=now()-RECEIPTS_MAX_RETENTION_PERIOD).adelete()
The deletes? Or the whole `prepare_receipts` thing?

even wasn't keen on beat for the zip generation: https://reeftechnologies.slack.com/archives/C06DMMT987M/p1715245099112639?thread_ts=1715244515.728119&cid=C06DMMT987M
and I was struggling to make it a normal celery task (conflicts with asyncio).

I'll move the deletions to a beat task.

2024-05-17 10:53 UTC, mzukowski-reef requested changes

2024-05-17 10:53 UTC, mzukowski-reef commented on miner/app/src/compute_horde_miner/miner/utils.py
> +    async with _prepare_receipts_lock:
this only make sense if you call it from the same asyncio loop - but you call it from celery task and django command - by default celery runs concurrent tasks in procesess.. and also in both places you run it in sync code so there is no reason for async here

2024-05-17 13:55 UTC, merged